### ISSUE TITLE
Totals should not exceed 24 hrs in a day

### ISSUE THREAD

**Issue by weedkiller** [martijnvwezel/muino-time-management#10]
Hello some totals for user are exceeding 24 hrs in a day ..  can we set limit for e.g. 

- [ ] no more than 18 hrs per day, and no more than 40 hrs week
- [ ] limit hrs per tasks totals

**Comment by martijnvwezel** [comment]
I expect tomorrow the updated version will be pushed!

**Comment by weedkiller** [comment]
when I have time, I can also help with and ASP backend web API... do you have the data base for this?

**Comment by martijnvwezel** [comment]
I had some internet issues, so hopefully I can sent the updated version soon.

**Comment by martijnvwezel** [comment]
After some thinking, this is not pushed. There were cases in my work where 2 types of projects should pay for the solution. The total hotfix was for that day 14 hours so 28 hours needed to be booked.

**Comment by martijnvwezel** [comment]
I can make this a feature setting. The next feature is going to be focused on Clockify integration.
